import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import walletsRouter from "./wallets";
import paymentsRouter from "./payments";
import requestsRouter from "./requests";
import dashboardRouter from "./dashboard";
import messagesRouter from "./messages";
import reportsRouter from "./reports";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import communityRouter from "./community";
import tournamentsRouter from "./tournaments";
import adminRouter from "./admin";
import adminAuthRouter from "./admin-auth";
import adminCommunityRouter from "./admin-community";
import modCommunityRouter from "./mod-community";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(walletsRouter);
router.use(paymentsRouter);
router.use(requestsRouter);
router.use(dashboardRouter);
router.use(messagesRouter);
router.use(reportsRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(communityRouter);
router.use(tournamentsRouter);
router.use(adminRouter);
router.use(adminAuthRouter);
router.use(adminCommunityRouter);
router.use(modCommunityRouter);

export default router;
